# Generated by Django 2.1.1 on 2019-06-25 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('netmask', models.GenericIPAddressField(blank=True, null=True, verbose_name='子网掩码')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '主机IP',
                'verbose_name_plural': '主机IP',
            },
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=50, verbose_name='主机名')),
                ('disk', models.FloatField(verbose_name='磁盘容量')),
                ('mem', models.FloatField(verbose_name='内存容量')),
                ('cpu', models.IntegerField(verbose_name='CPU核数')),
                ('net', models.IntegerField(verbose_name='网络带宽')),
                ('os_version', models.CharField(max_length=50, verbose_name='系统类型')),
                ('s_type', models.IntegerField(choices=[(1, '云服务器'), (2, '物理机'), (3, '虚拟机'), (4, 'PC机')], default=1, verbose_name='主机类型')),
                ('s_status', models.IntegerField(choices=[(1, '在使用'), (2, '备用中'), (3, '损坏')], default=2, verbose_name='设备状态')),
                ('mark', models.CharField(max_length=100, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.Ip', verbose_name='主机IP')),
            ],
            options={
                'verbose_name': '主机信息',
                'verbose_name_plural': '主机信息',
            },
        ),
    ]
